### ISSUE TITLE
[Question] Can we run swarm-updater once and exit?

### ISSUE THREAD

**Issue by shizunge** [codestation/swarm-updater#10]
Hi, 

Thank you for the watchtower similar implementation for swarm services.

I have not digged into the code, and thought you might already have the answer, which should be quicker.

Beside `--schedule`, could we run swarm-updater one shot? Run once and exit?
If there is one, I think it is not documented.

Thanks,
Shizun

**Comment by codestation** [comment]
I have added `--schedule=none` so it skips the cron manager and only run once.

**Comment by shizunge** [comment]
appreciate it!

**Comment by shizunge** [comment]
Another question:
How to start the swarm-updater and listen to the api updating services on demand, but do not run the cronjob?
Although I may not use it, I think for the completeness sake, swarm-updater should support this combination?

**Comment by codestation** [comment]
Yes, maybe changing `SCHEDULE=none` to just skip the cronjob (keeping the web server alive) and adding `SCHEDULE=once` to run the update job and exit.

For now i guess that setting `SCHEDULE="0 0 0 1 1 *"` (run the cronjob once a year) and `BLACKLIST=".*"` (skip everything) could a workaround.

I'll leave this for later as i want to refactor the web server and fix the corner case of calling the API endpoint while the cron job is running.
