### ISSUE TITLE
Multiarch image

### ISSUE THREAD

**Issue by mciupak** [codestation/swarm-updater#2]
It would be great to provide multiarch image e.g. for ARM32/64.

Any plans to do so?

**Comment by codestation** [comment]
Sounds good to me, I'll just have to find some free time to rewrite the .drome.yml script to build a multiarch image and push it to dockerhub. It shouldn't need any changes on the code.

**Comment by mciupak** [comment]
I do not have any experience with drone so I created github actions workflow to do the work for me. Take a look if it might work for you as well.

Feel free to reject PR if you prefer to do it with drone ci.

**Comment by codestation** [comment]
Closed by 70ccb1f2006e25c60ad417929f8170cf07dfc1bc. Pushed the images to GitHub as they seem less annoying than DockerHub rate limits.
